Move from pytype to mypy

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -43,10 +43,8 @@ jobs:
         run: uv run ruff check .
       - name: Run yamlfix
         run: uv run yamlfix .
-      - name: Run pytype static analysis
-        if: ${{ matrix.os != 'windows-latest' }}
-        run: uv run pytype --config pytype.cfg . || (echo "Pytype failed with code
-          $?"; exit 1)
+      - name: Run mypy static analysis
+        run: uv run mypy . || (echo "mypy failed with code $?"; exit 1)
       - name: Build application with PyInstaller
         run: uv run pyinstaller main.py --onefile --name MyApp --distpath dist/${{ matrix.os }}
       - name: Upload artifacts
