переход на pyqt6 с pyqt5, удаление pytype, uv pin python 3.11

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,7 +19,7 @@ jobs:
       - name: Restore uv cache
         uses: actions/cache@v4
         with:
-          path: .uv-cache
+          path: /tmp/.uv-cache
           key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
           restore-keys: |
             uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
@@ -31,22 +31,20 @@ jobs:
         if: ${{ matrix.os == 'windows-latest' }}
         run: irm https://astral.sh/uv/install.ps1 | iex
         shell: powershell
-      - name: Minimize uv cache
-        run: uv cache prune --ci
       - name: Set up Python
-        run: uv python install 3.11 3.12
+        run: uv python install 3.11
       - name: Install project dependencies
-        run: uv venv --python 3.11
+        run: uv venv
       - name: Check dependencies
         run: uv run pip list
       - name: Run ruff linter
         run: uv run ruff check .
       - name: Run yamlfix
         run: uv run yamlfix .
-      - name: Run pytype static analysis
-        if: ${{ matrix.os != 'windows-latest' }}
-        run: uv run pytype --config pytype.cfg . || (echo "Pytype failed with code
-          $?"; exit 1)
+#      - name: Run pytype static analysis
+#        if: ${{ matrix.os != 'windows-latest' }}
+#        run: uv run pytype --config pytype.cfg . || (echo "Pytype failed with code
+#          $?"; exit 1)
       - name: Build application with PyInstaller
         run: uv run pyinstaller main.py --onefile --name MyApp --distpath dist/${{ matrix.os }}
       - name: Upload artifacts
@@ -54,3 +52,5 @@ jobs:
         with:
           name: MyApp-${{ matrix.os }}
           path: dist/${{ matrix.os }}/MyApp*
+      - name: Minimize uv cache
+        run: uv cache prune --ci
